// Thin WebGPU renderer over the tested pure modules (math.ts, sceneBuild.ts).
// Everything that CAN be pure lives there; this file only owns GPU objects
// and the frame loop, so the untestable-without-a-browser surface stays
// minimal. WGSL is conservative WGSL-core — no extensions, no shorthand
// aliases — and the pipeline descriptors are exported as plain data so tests
// can validate their structure without a GPU.

import {
  type Mat4, type OrbitState, mat4Perspective, orbitViewMatrix,
} from './math';
import {
  EDGE_STRIDE, NEURON_STRIDE, type Scene3D, buildActivations,
} from './sceneBuild';

export function webgpuAvailable(): boolean {
  return typeof navigator !== 'undefined' && !!navigator.gpu;
}

// --- shaders ---------------------------------------------------------------------

// Both pipelines share this uniform block: mat4x4<f32> is 64 bytes, so the
// struct is 2×64 + 16 = 144 bytes = UNIFORM_FLOATS f32s, no implicit padding.
export const UNIFORM_FLOATS = 36;
export const DEPTH_FORMAT = 'depth24plus';

const UNIFORM_STRUCT_WGSL = `
struct Uniforms {
  view : mat4x4<f32>,
  proj : mat4x4<f32>,
  time : f32,
  pad0 : f32,
  pad1 : f32,
  pad2 : f32,
};
`;

// Neurons: instanced camera-facing quads (billboards) with a circular soft
// falloff; color = activation read from a storage buffer, mapped through an
// injectable `fn ramp(f32) -> vec3f` (Settings > Colors; generated by
// lib/Settings/colorSchemes.rampWgsl so 2D overlays and 3D always agree).
export const DEFAULT_RAMP_WGSL = `fn ramp(a : f32) -> vec3<f32> {
  var stops = array<vec3<f32>, 3>(vec3<f32>(0.23, 0.30, 0.75), vec3<f32>(0.87, 0.87, 0.87), vec3<f32>(0.71, 0.02, 0.15));
  let t = clamp(a, 0.0, 1.0) * 2.0;
  let i = min(u32(t), 1u);
  return mix(stops[i], stops[i + 1u], t - f32(i));
}`;

export const neuronWgsl = (rampFnWgsl: string = DEFAULT_RAMP_WGSL): string => `${UNIFORM_STRUCT_WGSL}
${rampFnWgsl}
@group(0) @binding(0) var<uniform> u : Uniforms;
@group(0) @binding(1) var<storage, read> activations : array<f32>;

struct VsOut {
  @builtin(position) position : vec4<f32>,
  @location(0) corner : vec2<f32>,
  @location(1) activation : f32,
};

@vertex
fn vs_main(
  @builtin(vertex_index) vertexIndex : u32,
  @builtin(instance_index) instanceIndex : u32,
  @location(0) center : vec3<f32>,
  @location(1) size : f32,
  @location(2) layerIndex : f32,
) -> VsOut {
  var corners = array<vec2<f32>, 6>(
    vec2<f32>(-1.0, -1.0), vec2<f32>(1.0, -1.0), vec2<f32>(-1.0, 1.0),
    vec2<f32>(-1.0, 1.0), vec2<f32>(1.0, -1.0), vec2<f32>(1.0, 1.0),
  );
  let corner = corners[vertexIndex];
  // Camera right/up = rows of the view rotation (columns of its transpose).
  let right = vec3<f32>(u.view[0].x, u.view[1].x, u.view[2].x);
  let up = vec3<f32>(u.view[0].y, u.view[1].y, u.view[2].y);
  let world = center + (right * corner.x + up * corner.y) * size;
  var out : VsOut;
  out.position = u.proj * (u.view * vec4<f32>(world, 1.0));
  out.corner = corner;
  out.activation = activations[instanceIndex];
  return out;
}

@fragment
fn fs_main(fsIn : VsOut) -> @location(0) vec4<f32> {
  let r = length(fsIn.corner);
  if (r > 1.0) {
    discard;
  }
  let falloff = 1.0 - smoothstep(0.55, 1.0, r);
  let a = clamp(fsIn.activation, 0.0, 1.0);
  let color = ramp(a);
  let alpha = falloff * (0.35 + 0.65 * a);
  return vec4<f32>(color * alpha, alpha);
}
`;

export const NEURON_WGSL = neuronWgsl();

// Edges: instanced line-list segments — vertex_index (0|1) picks endpoint a
// or b of the instance. weightSlot is reserved for a future weight buffer.
export const EDGE_WGSL = `${UNIFORM_STRUCT_WGSL}
@group(0) @binding(0) var<uniform> u : Uniforms;

struct VsOut {
  @builtin(position) position : vec4<f32>,
  @location(0) weightSlot : f32,
};

@vertex
fn vs_main(
  @builtin(vertex_index) vertexIndex : u32,
  @location(0) a : vec3<f32>,
  @location(1) b : vec3<f32>,
  @location(2) weightSlot : f32,
) -> VsOut {
  let world = mix(a, b, f32(vertexIndex));
  var out : VsOut;
  out.position = u.proj * (u.view * vec4<f32>(world, 1.0));
  out.weightSlot = weightSlot;
  return out;
}

@fragment
fn fs_main(fsIn : VsOut) -> @location(0) vec4<f32> {
  let alpha = 0.16;
  return vec4<f32>(vec3<f32>(0.55, 0.62, 0.75) * alpha, alpha);
}
`;

// --- pipeline descriptors (plain data, structurally testable) ----------------------

const PREMULTIPLIED_BLEND = {
  color: { srcFactor: 'one', dstFactor: 'one-minus-src-alpha', operation: 'add' },
  alpha: { srcFactor: 'one', dstFactor: 'one-minus-src-alpha', operation: 'add' },
};

// Transparent instances never write depth: the buffer is there for future
// opaque geometry, and blended dots/lines stay order-independent enough.
const NO_WRITE_DEPTH = {
  format: DEPTH_FORMAT,
  depthWriteEnabled: false,
  depthCompare: 'less',
};

export function neuronPipelineDescriptor(module: GPUShaderModule, format: GPUTextureFormat) {
  return {
    label: 'viz3d-neurons',
    layout: 'auto',
    vertex: {
      module,
      entryPoint: 'vs_main',
      buffers: [{
        arrayStride: NEURON_STRIDE * 4,
        stepMode: 'instance',
        attributes: [
          { shaderLocation: 0, offset: 0, format: 'float32x3' }, // center
          { shaderLocation: 1, offset: 12, format: 'float32' }, // size
          { shaderLocation: 2, offset: 16, format: 'float32' }, // layerIndex
        ],
      }],
    },
    fragment: {
      module,
      entryPoint: 'fs_main',
      targets: [{ format, blend: PREMULTIPLIED_BLEND }],
    },
    primitive: { topology: 'triangle-list', cullMode: 'none' },
    depthStencil: NO_WRITE_DEPTH,
  };
}

export function edgePipelineDescriptor(module: GPUShaderModule, format: GPUTextureFormat) {
  return {
    label: 'viz3d-edges',
    layout: 'auto',
    vertex: {
      module,
      entryPoint: 'vs_main',
      buffers: [{
        arrayStride: EDGE_STRIDE * 4,
        stepMode: 'instance',
        attributes: [
          { shaderLocation: 0, offset: 0, format: 'float32x3' }, // a
          { shaderLocation: 1, offset: 12, format: 'float32x3' }, // b
          { shaderLocation: 2, offset: 24, format: 'float32' }, // weightSlot
        ],
      }],
    },
    fragment: {
      module,
      entryPoint: 'fs_main',
      targets: [{ format, blend: PREMULTIPLIED_BLEND }],
    },
    primitive: { topology: 'line-list' },
    depthStencil: NO_WRITE_DEPTH,
  };
}

// --- renderer ---------------------------------------------------------------------

export interface Viz3DRenderer {
  setCamera(state: OrbitState): void;
  /** Swaps the whole scene (rebuild button); resets activations too. */
  setScene(scene: Scene3D): void;
  /** Per-neuron f32 array in scene order (see sceneBuild.buildActivations). */
  setActivations(values: Float32Array): void;
  destroy(): void;
}

export async function createViz3DRenderer(
  canvas: HTMLCanvasElement, scene: Scene3D, camera: OrbitState,
  rampFnWgsl?: string,
): Promise<Viz3DRenderer> {
  const gpu = typeof navigator !== 'undefined' ? navigator.gpu : undefined;
  if (!gpu) throw new Error('WebGPU is not available in this browser');
  const adapter = await gpu.requestAdapter();
  if (!adapter) throw new Error('No WebGPU adapter available');
  const device = await adapter.requestDevice();
  const context = canvas.getContext('webgpu') as unknown as GPUCanvasContext | null;
  if (!context) throw new Error('Could not create a WebGPU canvas context');
  const format = gpu.getPreferredCanvasFormat();
  context.configure({ device, format, alphaMode: 'premultiplied' });

  const neuronModule = device.createShaderModule({ label: 'viz3d-neurons', code: neuronWgsl(rampFnWgsl) });
  const edgeModule = device.createShaderModule({ label: 'viz3d-edges', code: EDGE_WGSL });
  const neuronPipeline = device.createRenderPipeline(neuronPipelineDescriptor(neuronModule, format));
  const edgePipeline = device.createRenderPipeline(edgePipelineDescriptor(edgeModule, format));

  const uniformBuffer = device.createBuffer({
    label: 'viz3d-uniforms',
    size: UNIFORM_FLOATS * 4,
    usage: GPUBufferUsage.UNIFORM | GPUBufferUsage.COPY_DST,
  });
  const uniformValues = new Float32Array(UNIFORM_FLOATS);
  const startedAt = (typeof performance !== 'undefined' ? performance.now() : 0);

  let cameraState = camera;
  let destroyed = false;
  let frameHandle = 0;
  let neuronBuffer: GPUBuffer | null = null;
  let edgeBuffer: GPUBuffer | null = null;
  let activationBuffer: GPUBuffer | null = null;
  let neuronBindGroup: GPUBindGroup | null = null;
  let edgeBindGroup: GPUBindGroup | null = null;
  let neuronCount = 0;
  let edgeCount = 0;
  let depthTexture: GPUTexture | null = null;
  let depthView: GPUTextureView | null = null;
  let depthWidth = 0;
  let depthHeight = 0;

  const releaseScene = () => {
    neuronBuffer?.destroy();
    edgeBuffer?.destroy();
    activationBuffer?.destroy();
    neuronBuffer = null;
    edgeBuffer = null;
    activationBuffer = null;
  };

  const uploadScene = (next: Scene3D) => {
    releaseScene();
    neuronCount = next.neuronCount;
    edgeCount = next.edgeCount;
    neuronBuffer = device.createBuffer({
      label: 'viz3d-neuron-instances',
      size: Math.max(next.neurons.byteLength, 4),
      usage: GPUBufferUsage.VERTEX | GPUBufferUsage.COPY_DST,
    });
    device.queue.writeBuffer(neuronBuffer, 0, next.neurons);
    edgeBuffer = device.createBuffer({
      label: 'viz3d-edge-instances',
      size: Math.max(next.edges.byteLength, 4),
      usage: GPUBufferUsage.VERTEX | GPUBufferUsage.COPY_DST,
    });
    device.queue.writeBuffer(edgeBuffer, 0, next.edges);
    activationBuffer = device.createBuffer({
      label: 'viz3d-activations',
      size: Math.max(next.activationSlots * 4, 4),
      usage: GPUBufferUsage.STORAGE | GPUBufferUsage.COPY_DST,
    });
    device.queue.writeBuffer(activationBuffer, 0, buildActivations(next));
    neuronBindGroup = device.createBindGroup({
      label: 'viz3d-neuron-bindings',
      layout: neuronPipeline.getBindGroupLayout(0),
      entries: [
        { binding: 0, resource: { buffer: uniformBuffer } },
        { binding: 1, resource: { buffer: activationBuffer } },
      ],
    });
    edgeBindGroup = device.createBindGroup({
      label: 'viz3d-edge-bindings',
      layout: edgePipeline.getBindGroupLayout(0),
      entries: [{ binding: 0, resource: { buffer: uniformBuffer } }],
    });
  };
  uploadScene(scene);

  const resizeIfNeeded = () => {
    const ratio = (typeof window !== 'undefined' && window.devicePixelRatio) || 1;
    const width = Math.max(1, Math.floor(canvas.clientWidth * ratio) || canvas.width || 1);
    const height = Math.max(1, Math.floor(canvas.clientHeight * ratio) || canvas.height || 1);
    if (canvas.width !== width) canvas.width = width;
    if (canvas.height !== height) canvas.height = height;
    if (depthTexture && depthWidth === width && depthHeight === height) return;
    depthTexture?.destroy();
    depthTexture = device.createTexture({
      label: 'viz3d-depth',
      size: { width, height },
      format: DEPTH_FORMAT,
      usage: GPUTextureUsage.RENDER_ATTACHMENT,
    });
    depthView = depthTexture.createView();
    depthWidth = width;
    depthHeight = height;
  };

  const writeUniforms = () => {
    const aspect = canvas.width / Math.max(1, canvas.height);
    const view: Mat4 = orbitViewMatrix(cameraState);
    const proj: Mat4 = mat4Perspective(
      Math.PI / 4, aspect, 0.1, cameraState.distance * 20 + 100,
    );
    uniformValues.set(view, 0);
    uniformValues.set(proj, 16);
    const now = typeof performance !== 'undefined' ? performance.now() : 0;
    uniformValues[32] = (now - startedAt) / 1000;
    device.queue.writeBuffer(uniformBuffer, 0, uniformValues);
  };

  const frame = () => {
    if (destroyed) return;
    frameHandle = requestAnimationFrame(frame);
    resizeIfNeeded();
    if (!depthView || !neuronBuffer || !edgeBuffer || !neuronBindGroup || !edgeBindGroup) return;
    writeUniforms();
    const encoder = device.createCommandEncoder();
    const pass = encoder.beginRenderPass({
      colorAttachments: [{
        view: context.getCurrentTexture().createView(),
        clearValue: {
          r: 0.04, g: 0.05, b: 0.09, a: 1,
        },
        loadOp: 'clear',
        storeOp: 'store',
      }],
      depthStencilAttachment: {
        view: depthView,
        depthClearValue: 1,
        depthLoadOp: 'clear',
        depthStoreOp: 'store',
      },
    });
    if (edgeCount > 0) {
      pass.setPipeline(edgePipeline);
      pass.setBindGroup(0, edgeBindGroup);
      pass.setVertexBuffer(0, edgeBuffer);
      pass.draw(2, edgeCount);
    }
    if (neuronCount > 0) {
      pass.setPipeline(neuronPipeline);
      pass.setBindGroup(0, neuronBindGroup);
      pass.setVertexBuffer(0, neuronBuffer);
      pass.draw(6, neuronCount);
    }
    pass.end();
    device.queue.submit([encoder.finish()]);
  };
  frameHandle = requestAnimationFrame(frame);

  return {
    setCamera(state) {
      cameraState = state;
    },
    setScene(next) {
      uploadScene(next);
    },
    setActivations(values) {
      if (activationBuffer) device.queue.writeBuffer(activationBuffer, 0, values);
    },
    destroy() {
      if (destroyed) return;
      destroyed = true;
      cancelAnimationFrame(frameHandle);
      releaseScene();
      uniformBuffer.destroy();
      depthTexture?.destroy();
      device.destroy();
    },
  };
}
