version: '2'
services:
  pvnn_reverse_proxy_and_static:
    build:
      context: src/
      dockerfile: Dockerfile
    ports:
      - 80:9080
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - pvnn_net

  pvnn_api:
    build:
      context: src/api/
      dockerfile: Dockerfile
    expose:
      - 5000
    networks:
      - pvnn_net

networks:
  pvnn_net:
