version: '2'
services:
  nnvp_reverse_proxy_and_static:
    build:
      context: src/
      dockerfile: Dockerfile
    ports:
      - 80:9080
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - nnvp_net

  nnvp_api:
    build:
      context: src/api/
      dockerfile: Dockerfile
    expose:
      - 5000
    networks:
      - nnvp_net

networks:
  nnvp_net:
